fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
#  registration:
#    form:
#      type: App\Form\RegistrationType
  from_email:
    address: "yterrana@hotmail.fr"
    sender_name: "mlcpro"