fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
  prefix: /

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /rrr
